apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-basic
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "bobocode-jpa-ip"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bobocode-jpa-service
                port:
                  number: 8080